In [1]:
import numpy as np

In [3]:
s=np.array([2,3,4,5,6,7])
s

array([2, 3, 4, 5, 6, 7])

In [4]:
print(type(s))

<class 'numpy.ndarray'>


In [5]:
print(s.dtype)

int32


In [6]:
s1=np.array([2.3,4.5,6.8,9.8,7.5])
print(s1.dtype)

float64


In [8]:
a=np.array(5)                    # zero dimension array
print(a.ndim)

0


In [9]:
a=np.array(6)
print(a.ndim)

0


In [16]:
a1=np.array([2,3,4,5,6,7])               # one dimension arreay
print(a1.ndim)
print(a1.shape)

1
(6,)


In [12]:
b=np.array([1.2,4.5,7.8,9.5,6.3])
print(b.ndim)

1


In [17]:
a2=np.array([[1,2,3,4,5,6,7]])            # two dimension array
print(a2.ndim)
print(a2.shape)

2
(1, 7)


In [18]:
c=np.array([[1.2,2.3,4.5,6.5,7.8]])
print(c.ndim)
print(c.shape)

2
(1, 5)


In [20]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])           # 3 dimension array
print(a3.ndim)
print(a3.shape)

3
(1, 3, 3)


In [21]:
d=np.array([[[1,1,1],[2,2,2],[3,3,3],[4,4,4]],[[5,5,5],[6,6,6],[7,7,7],[8,8,8]]])
print(d)

[[[1 1 1]
  [2 2 2]
  [3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]
  [7 7 7]
  [8 8 8]]]


In [22]:
print(d.ndim)

3


In [23]:
print(d.shape)

(2, 4, 3)


In [24]:
a4=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
a4

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [25]:
print(a4.ndim)

4


In [26]:
print(a4.shape)

(1, 1, 3, 3)


In [27]:
x=np.array([[[[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]]]])

In [28]:
x

array([[[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]]])

In [29]:
print(x.ndim)
print(x.shape)

4
(1, 2, 3, 3)


In [30]:
# concatenate

In [33]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,10,11])
a=np.concatenate((arr1,arr2))
a

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [44]:
# reshape

In [37]:
s=np.array([11,22,33,44,55,66,77])
s.reshape(7,1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77]])

In [39]:
s1=np.array([11,22,33,44,55,66,77,88])
s1.reshape(2,4)


array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [40]:
s1.reshape(4,2)

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [42]:
s1.reshape(1,8)

array([[11, 22, 33, 44, 55, 66, 77, 88]])

In [43]:
s1.reshape(8,1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77],
       [88]])

In [46]:
ar2=np.array([[11,22,33,44],[55,66,77,88]])
ar2.reshape(4,2)

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [47]:
ar2.reshape(2,4)

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [48]:
ar2.reshape(1,8)

array([[11, 22, 33, 44, 55, 66, 77, 88]])

In [49]:
ar2.reshape(8,1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77],
       [88]])

In [51]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
ar3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
ar3.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
ar3.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [56]:
ar3.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [57]:
ar3.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [58]:
ar3.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [59]:
# split

In [60]:
arr=np.array([1,2,3])
np.array_split(arr,3)

[array([1]), array([2]), array([3])]

In [61]:
np.array_split(arr,2)

[array([1, 2]), array([3])]

In [62]:
np.array_split(arr,4)

[array([1]), array([2]), array([3]), array([], dtype=int32)]

In [64]:
print(np.array_split(arr,6))

[array([1]), array([2]), array([3]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [65]:
ar1=np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(ar1,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


In [66]:
print(np.array_split(ar1,4))

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [67]:
print(np.array_split(ar1,7))

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8]), array([9])]


In [68]:
print(np.array_split(ar1,9))

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]


In [69]:
ar2=np.array([[1,2,3],[4,5,6]])
print(np.array_split(ar2,4))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]


In [74]:
print(np.array_split(ar2,6))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]


In [75]:
print(np.array_split(ar2,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [78]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,22]]])
print(np.array_split(ar3,2))

[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 22]]]), array([], shape=(0, 4, 3), dtype=int32)]


In [79]:
print(np.array_split(ar3,4))

[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 22]]]), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32)]


In [80]:
print(np.array_split(ar3,3))

[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 22]]]), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32)]


In [81]:
print(np.array_split(ar3,12))

[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 22]]]), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32), array([], shape=(0, 4, 3), dtype=int32)]


In [82]:
# where

In [84]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.where(a==5))

(array([4], dtype=int64),)


In [85]:
print(np.where(a==8))

(array([7], dtype=int64),)


In [86]:
ar=np.array([11,22,33,44,55,66,77,88,99])
n=int(input("Enter the value : "))
print(np.where(ar==n))

Enter the value : 77
(array([6], dtype=int64),)


In [87]:
ar=np.array([11,22,33,44,55,66,77,88,99])
n=int(input("Enter the value : "))
print(np.where(ar==n))

Enter the value : 100
(array([], dtype=int64),)


In [88]:
arr=np.array([[455,789,321,852],[489,741,963,357]])
np.where(arr==455)

(array([0], dtype=int64), array([0], dtype=int64))

In [89]:
np.where(arr==741)

(array([1], dtype=int64), array([1], dtype=int64))

In [90]:
np.where(arr==963)

(array([1], dtype=int64), array([2], dtype=int64))

In [91]:
arr3=np.array([[[258,456,753,951],[444,785,985,325]],[[159,999,746,364],[666,555,627,391]]])

In [92]:
print(arr3.ndim)

3


In [93]:
np.where(arr3==746)

(array([1], dtype=int64), array([0], dtype=int64), array([2], dtype=int64))

In [94]:
np.where(arr3==627)

(array([1], dtype=int64), array([1], dtype=int64), array([2], dtype=int64))

In [95]:
# sort

In [96]:
ar1=np.array([700,852,963,1,5,987,65,2637,984])
np.sort(ar1)

array([   1,    5,   65,  700,  852,  963,  984,  987, 2637])

In [97]:
np.sort(ar1)[::-1]

array([2637,  987,  984,  963,  852,  700,   65,    5,    1])

In [98]:
ar2=np.array([[1,3,5,7,8],[47,98,65,3,24],[78,99,55,11,46]])
np.sort(ar2)

array([[ 1,  3,  5,  7,  8],
       [ 3, 24, 47, 65, 98],
       [11, 46, 55, 78, 99]])

In [99]:
np.sort(ar2)[::-1]

array([[11, 46, 55, 78, 99],
       [ 3, 24, 47, 65, 98],
       [ 1,  3,  5,  7,  8]])